### ISSUE TITLE
Magento 2.1.x /  Import failed by a "catalog_product_entity_decimal.entity_type_id column not found" sql error 

### ISSUE THREAD

**Issue by mohamed-badaoui** [macopedia/magmi-git#1]
Magento 2.1.x /  No products were imported due to a sql error on :
DELETE FROM catalog_product_entity_decimal WHERE entity_type_id='4' AND attribute_id IN (81,98,121,78) AND store_id IN (0) AND entity_id='67'
ROLLBACK

Indeed, entity_type_id column does not exist in catalog_product_entity_decimal table.

**Comment by idziakjakub** [comment]
Hello Mohamed, thank you for notification. Images import was tested by other contributor, maybe he didin't use "media_gallery" column. Have you tried to fix this issue? Probably we need to find places in code where "catalog_product_entity_decimal" are used and refactor columns (column "entity_type_id" was deprecated for attribute tables in Magento 2.1).

**Comment by mohamed-badaoui** [comment]
No finally I gave up to make it works.

After some research, I simply use original Magento2 export/import system. 
And it works pretty well and it is quite fast.

**Comment by geethq** [comment]
i have the same issue. trying to import gallery or media_gallery images is giving various errors. 
it will be great if media_gallery imports can be fixed.

**Comment by tmotyl** [comment]
image import was solved with https://github.com/macopedia/magmi-git/pull/13 please test again
