### ISSUE TITLE
Magmi on PHP 8.1 

### ISSUE THREAD

**Issue by JosephGourvenec** [macopedia/magmi-git#102]
Hi Guys,

Been trying to run this with Magento 2.4.4 on PHP 8.1 but Magmi fails to load, so had to revert down to PHP 7.4.

1. Should Magmi work on PHP 8.1?
If so what changes do i need to make to get it to work 

2. If not, will this be addressed in the package to accommodate PHP 8.1

Cheers,
Joe

**Comment by cbtrident** [comment]
not sure if they working on it but am fixing it for my web site
if it work i put it up for people to try 
so far fixed two files and it looking good but not start the import yet just got the memu show with no errors

**Comment by cbtrident** [comment]
ok it working and i put up a pull request
the datetime for config file is not looking right but it working and i have imported 
5622 items (100%)

**Comment by JosephGourvenec** [comment]
> ok it working and i put up a pull request the datetime for config file is not looking right but it working and i have imported 5622 items (100%)

Hey did you have any joy in getting Magmi to work with PHP 8?

**Comment by cbtrident** [comment]
seem to work there a pull request at the tope for it never got to fix the gui date but it work

**Comment by Nofear262** [comment]
Hey, where can i find this version. We went to 8.1 and i can't get it to work. Did get a 500 error on it.

**Comment by cbtrident** [comment]
check pull request

**Comment by Henrik41** [comment]
You have a mistake in the code. You need to add "}" in line 1873 in this file: magmi/engines/magmi_productimportengine.php

**Comment by cbtrident** [comment]
pull request was done and in main branch

**Comment by tmotyl** [comment]
please try the magento2 branch https://github.com/macopedia/magmi-m2 
if it's not working, please open new issue with description how to reproduce

**Comment by JosephGourvenec** [comment]
Hi Guys,

Just testing M2.4.6 with PHP8.1 now Magmi has a new pull for php8.1 support. 

Configured everything as it should be with ini file, etc as i always have with 100% the correct details got from env.php too

I keep getting "Please create magmi.ini file in magmi/conf directory , by copying & editing magmi.ini.default file and filling appropriate values" 

It is 100% there, what could I be missing please?

Cheers,
Joe

**Comment by Henrik41** [comment]
You probably have a permission issue. Check your permissions. Also please check your error logs. Are you using Apache or Nginx?
