### ISSUE TITLE
Image Attribute Processor Issue

### ISSUE THREAD

**Issue by shawkatvirtuos** [macopedia/magmi-git#15]
Hello ,

The image attribute processor is not working in case of gallary images because now magento has 3 tables for galary images. 

catalog_product_entity_media_gallery
catalog_product_entity_media_gallery_value
catalog_product_entity_media_gallery_value_to_entity

But if I check the code , then I can see it has code for only 2 tables.

For reference I have attached my file 

Please check and let me know if I am doing anything wrong.
[9.csv.zip](https://github.com/macopedia/magmi-git/files/1568680/9.csv.zip)

**Comment by pwaszkis** [comment]
Hello,
Thank you for reporting the issue. As I see in [imageitattributeemprocessor.php](https://github.com/macopedia/magmi-git/blob/magento2/magmi/plugins/extra/itemprocessors/imageprocessor/imageitattributeemprocessor.php), there are executed queries for all of the 3 tables you specify, so me question is if You used tool in the newest version?

If there still will be problem with importing images I can test atteched csv file, but I please to tell me which Magento version problem occured on.

**Comment by shawkatvirtuos** [comment]
Thanks for sharing the same , the version I have might be the old. Now I copied the same , but still I am not able to get the gallery images. Can you please check the attached sheet , if I am doing anything wrong.

**Comment by pwaszkis** [comment]
Ok, on which Magento version can I test your sheet?

**Comment by shawkatvirtuos** [comment]
Thanks a lot in advance , I am using magento 2.2.1 , but as it is magmi , so hope it will work with magento 2.1 as well

**Comment by shawkatvirtuos** [comment]
@pwaszkis  did you checked ? I request you if you please can help me with this, I really not able to find a way out for this.

**Comment by pwaszkis** [comment]
@shawkatvirtuos After minor fix product import with images works well on my magento instance. Using comma between image paths in media_gallery column caused misalignment of the further columns. I suggest using other csv separator (i.e ";"), and I hope it will work :)

**Comment by shawkatvirtuos** [comment]
Hello @pwaszkis  thanks for your response , if you check I actually have a single value , so should I need to use a ";" at the end ?

**Comment by shawkatvirtuos** [comment]
Hello @pwaszkis  Can you please send me a sample sheet. It will really help me a lot. I tried to use semicolon(";") , between 2 gallery images , but it actually does not help.

**Comment by shawkatvirtuos** [comment]
I am really not able to make it work , if @pwaszkis  or @tmotyl  is able to share a dummy sheet with me , I will be very thankful to both of you. Please help me this. I really need your help. I am not able to resolve this

**Comment by shawkatvirtuos** [comment]
If I check the database then my media_gallery data is not getting inserted in any of the database table. I am not able to understand the reason. Please please please help me with this. I will always be grateful to both you @pwaszkis  @tmotyl 

Below is my latest sheet and magmi configuration
![magmi](https://user-images.githubusercontent.com/29040632/34163656-541cf636-e4fd-11e7-9e42-28b924eb6727.png)

[14.csv.zip](https://github.com/macopedia/magmi-git/files/1572128/14.csv.zip)

**Comment by pwaszkis** [comment]
@shawkatvirtuos In fact there was a problem with import media_gallery attribute. [#16](https://github.com/macopedia/magmi-git/pull/16) should fix your problem.

**Comment by shawkatvirtuos** [comment]
@pwaszkis  Actually I also checked the same , thanks for the update. One thing I want to know is , I want to delete  all the previous images if I update the product with new images
