### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cea.is_configurable' in 'on clause'

### ISSUE THREAD

**Issue by to8gal** [macopedia/magmi-git#27]
after upgrading to Magento 2.2.4 when trying to import configurable products I got the above error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cea.is_configurable' in 'on clause'
`
other warning say:

`Potential assignment problem, specific model found for select attribute => size(Magento\Eav\Model\Entity\Attribute\Source\Table)
`

**Comment by milossh** [comment]
Have you managed to resolve this?

**Comment by to8gal** [comment]
This problem meant the simple product had not the attribute they need to make the automatic link with the configurable, I made that connection manually cause at the moment I need the data just on my dev site, so is a NO the problem is not solved.

**Comment by milossh** [comment]
In my case, said simple products do actually have all the attributes as configurable product, but I'm still getting said error. This is on Magento 2.2.x

**Comment by to8gal** [comment]
Yes of course they have (sorry bad writing) is just that for some reason they cannot be read and used.

**Comment by milossh** [comment]
Ok, makes sense. But how did you actually fix this?

**Comment by to8gal** [comment]
I fixed it manually cause I just need some record to work with the dev, I will deal with the problem later as I am sure is something solvable.

**Comment by milossh** [comment]
Ok, but how did you fix it? What did you actually do?

**Comment by to8gal** [comment]
I insert the products manually, one by one, just a few of them

**Comment by idziakjakub** [comment]
@to8gal are you sure that your CSV file has correct data in "simples_skus" (all simple related products separated by comma) and "configurable_attributes" (all attribute codes used for configuration separated by comma)?
I think if you enable "Configurable Item processor" plugin and use CSV file without this columns there can be errors in import because magmi cannot match simple-configurable link.
You can send your example CSV file and I can check it.

**Comment by to8gal** [comment]
Hello Guys,

Thanks for the interest but right now I am taking care of a whole other aspect of the site, so really cannot take care of this right now, anyway simples_skus should not be needed if Perform simples/configurable link is set to yes, and of course there is configurable_attributes with the right attribute on it
