### ISSUE TITLE
Support Image attributes processor - media_gallery column?

### ISSUE THREAD

**Issue by timleeuchees** [macopedia/magmi-git#4]
Hi,

Thanks for the great magmi for Magento 2. Does this magmi support Image attributes processor - media_gallery column? After adding this column (media_gallery) to csv file, it will import fail. Error message as below:
> SKU Test-6 - 1 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'emg.entity_id' in 'where clause' -
> SKU Test-6 - 2 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'emg.entity_id' in 'where clause' - ERROR ON RECORD #1

Tim

**Comment by idziakjakub** [comment]
Hi Tim, images import was tested by one of contributors. This issue is related to: #1

**Comment by timleeuchees** [comment]
Thanks and I'll follow #1 for issue status.
