### ISSUE TITLE
wrong product image folder location 2.1

### ISSUE THREAD

**Issue by geethq** [macopedia/magmi-git#5]
image importer creates the old folder structure for 1.9 (magento root/media/catalog/product/) instead of magento 2.1 magento root/pub/media/catalog/product/
so the images are not displaying after the import. have to move the product folder to correct folder patch to get the images working.

**Comment by geethq** [comment]
i have solved this by editing plugins/extra/itemprocessors/imageprocessor/imageitattributeemprocessor.php
line 463 
$l2d = "media/catalog/product/$i1/$i2";
to
$l2d = "pub/media/catalog/product/$i1/$i2";

**Comment by idziakjakub** [comment]
If you have solved this problem please commit your changes and make pull request.

**Comment by geethq** [comment]
@idziakjakub sorry i'm new to using github. ill check how to commit changes and make pull requests.

**Comment by tmotyl** [comment]
fixed with https://github.com/macopedia/magmi-git/pull/10/files
