### ISSUE TITLE
Magento 2 Image Gallery saving

### ISSUE THREAD

**Issue by martinwhiteley** [macopedia/magmi-git#6]
Hi guys,

Do you have an eta on when this feature will be fixed in the M2 version?

Thanks, Martin

**Comment by tmotyl** [comment]
Hi,
can you please check if https://github.com/macopedia/magmi-git/pull/9 solved the issue for you?

**Comment by martinwhiteley** [comment]
Hi, and thanks for your reply, really appreciated.

 

I made the code change on our dev server but it didn’t import that extra image, although it didn’t report an error either.  It DID import the base image in the “image” column.

 

I’ve attached the sample import file for you to review in case I’ve got it wrong.

 

Also, having trouble with indexing on the fly.  I have configured path to product to include category but my urls are not clean eg

 

https://bpi.tinsoldier.net.nz/catalog/product/view/id/23/s/foamalite-xpress/category/23/

 

if you can give me some guidance, or direct me to someone who can, that would be very useful.

 

Finally, I will need to be able to import files into Magento eg PDF’s.  Is there any work being done on Magmi to support this?  I understand Magento 2 doesn’t support product attributes with type file natively but I believe it’s possible to enable this.  This is one half of the problem, the other being the Magmi side.  Any help appreciated.

 

Thanks again for your help, really appreciate it.

 

Cheers, Martin

**Comment by tmotyl** [comment]
Hi,
Can you attach a sample file to the github issue, seems the attachement was not added via mail reply.

**Comment by martinwhiteley** [comment]
[sample.import.zip](https://github.com/macopedia/magmi-git/files/1381216/sample.import.zip)

**Comment by martinwhiteley** [comment]
Hi, I’ve attached again to this email and also uploaded to the github issue.

 

Thanks, Martin

**Comment by martinwhiteley** [comment]
Hi all, sorry to hassle but was hoping a response to the below, even if just
a quick update.

 

Any help appreciated.

 

Thanks, Martin

 

 

 

 

Hi,

 

Congratulations on Magmi.  Working pretty well so far.

 

I'm not sure whether it was you who answered by question posted on github.
I have another issue and am seeking advice so I'll ask everything here.

 

1)      I made a suggested code change
(https://github.com/macopedia/magmi-git/pull/9) to correct the issue with
gallery image upload but that didn't seem to work.  I've attached the tested
import file.

2)      Also, having trouble with indexing on the fly.  I have configured
path to product to include category but my urls are not clean eg
https://bpi.tinsoldier.net.nz/catalog/product/view/id/23/s/foamalite-xpress/
category/23/ so any help here would be good

3)      I seem to be having issues importing images like
https://pim.plytix.com/download/v1/assets/2e/5e/47/59/59475e2e97b19210e5c998
bb/images/af/60/82/59/598260afd42cad7b3ece0ef4/Osprey_AlfredForns-AudubonPot
ographyAward.jpg?v=20173003010856290000 from Plytix.  As you can see the
image is publicly accessible but I'm getting some sort of corrupted image
with a small files size imported.  Could it be the parameter on the end? I
have tried importing a local file with the parameters removed from that path
without success.  If I download the image to my desktop and upload to a
product in magento its fine   I have tried to rewrite the image name during
processing but that is not helping

4)      Finally, I will need to be able to import files into Magento eg
PDF's.  Is there any work being done on Magmi to support this?  I understand
Magento 2 doesn't support product attributes with type file natively but I
believe it's possible to enable this.  This is one half of the problem, the
other being the Magmi side.  Any help appreciated.

 

Thanks for your help.

 

Cheers, Martin

**Comment by martinwhiteley** [comment]
Hi guys, just wanted to check that you received this email.  If you can
possibly provide a response that would be useful.

 

Thanks, Martin

 

 

 

 

 

 

 

Hi all, sorry to hassle but was hoping a response to the below, even if just
a quick update.

 

Any help appreciated.

 

Thanks, Martin

 

 

 

 

Hi,

 

Congratulations on Magmi.  Working pretty well so far.

 

I'm not sure whether it was you who answered by question posted on github.
I have another issue and am seeking advice so I'll ask everything here.

 

1)      I made a suggested code change
(https://github.com/macopedia/magmi-git/pull/9) to correct the issue with
gallery image upload but that didn't seem to work.  I've attached the tested
import file.

2)      Also, having trouble with indexing on the fly.  I have configured
path to product to include category but my urls are not clean eg
https://bpi.tinsoldier.net.nz/catalog/product/view/id/23/s/foamalite-xpress/
category/23/ so any help here would be good

3)      I seem to be having issues importing images like
https://pim.plytix.com/download/v1/assets/2e/5e/47/59/59475e2e97b19210e5c998
bb/images/af/60/82/59/598260afd42cad7b3ece0ef4/Osprey_AlfredForns-AudubonPot
ographyAward.jpg?v=20173003010856290000 from Plytix.  As you can see the
image is publicly accessible but I'm getting some sort of corrupted image
with a small files size imported.  Could it be the parameter on the end? I
have tried importing a local file with the parameters removed from that path
without success.  If I download the image to my desktop and upload to a
product in magento its fine   I have tried to rewrite the image name during
processing but that is not helping

4)      Finally, I will need to be able to import files into Magento eg
PDF's.  Is there any work being done on Magmi to support this?  I understand
Magento 2 doesn't support product attributes with type file natively but I
believe it's possible to enable this.  This is one half of the problem, the
other being the Magmi side.  Any help appreciated.

 

Thanks for your help.

 

Cheers, Martin

**Comment by tmotyl** [comment]
fixed with https://github.com/macopedia/magmi-git/pull/13 please retest

**Comment by marco7319** [comment]
Hello
what is the latest stable version magmi for magenti 3.2.3?
is it stable?
I am currently using this one:
but the images put in the "additional_images" column of my csv do not display in magento 3.2.3
and my url links contain  .../catalog/product/view/id/2088/s/...  /category/48/

THANK YOU VERY MUCH
