### ISSUE TITLE
cannot create product, no attribute_set defined

### ISSUE THREAD

**Issue by dshaw002** [macopedia/magmi-git#8]
Thanks for forking this to Magento 2.

I'm running the Magmi import and whenever I do, I get this message for my products under errors:

SKU XXXXX - cannot create product sku:XXXXX, no attribute_set defined

Any idea on how to deal with this? Should I format my CSV import file different for Magento 2 than Magento 1? Any help would be appreciated.

**Comment by shyang292** [comment]
@dshaw002 the column name for attribute set should be "attribute_set" instead of "attribute_set_code"

**Comment by kaybeudeker** [comment]
@dshaw002 in case of the default Magento attribute set, make sure you use a capital 'D' in your CSV file.

**Comment by tmotyl** [comment]
@dshaw002 please provide an csv file which is failing for you, otherwise I will close the issue in a few days.

**Comment by tmotyl** [comment]
closing issue due to lack of the feedback
