### ISSUE TITLE
Delete list of skus

### ISSUE THREAD

**Issue by raybog** [macopedia/magmi-git#88]
Hi Team,

Is there a way in magmi to remove a list of SKUs from M2?

Thanks

**Comment by kojoman** [comment]
Hey @raybog, 

Start by making sure you've added the "Product Deleter" option to to the Magmi profile you're using.  Then, add a column, "magmi:delete" whose values should be 1 to delete and 0 to not delete.  

You can check the documentation [here](http://wiki.magmi.org/index.php?title=Product_Deleter). 

I hope this helps.
